name: Update Clicks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  update-clicks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.89.4'
          extended: true

      - name: Build
        run: |
          git config core.quotePath false
          hugo

      - name: Install requirements
        run: pip install requests pyaml

      - run: python scripts/UpdateClicks.py

      - name: Commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git commit -am "chore: update clicks"

      - name: Push changes
        uses: ad-m/github-push-action@4dcce6dea3e3c8187237fc86b7dfdc93e5aaae58
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Trigger Deploy
        uses: benc-uk/workflow-dispatch@b8ac4001bdf17685419a1b65af6fa92fc9a3de0e
        with:
          workflow: Deploy
          token: ${{ secrets.PERSONAL_TOKEN }}
